name: cmu-lifelong-ed-temp

services:
    postgres:
      image: postgres:latest
      container_name: cmu_lifelong_ed_db_temp
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        SECRET_KEY: ${SECRET_KEY}
      ports:
        - "${DATABASE_PORT}:5433"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - mynetwork

    pgadmin:
      image: dpage/pgadmin4:latest
      container_name: cmu_lifelong_ed_pgadmin_temp
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "${PGADMIN_PORT}:81"
      depends_on:
        - postgres
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      networks:
        - mynetwork
  
volumes:
  postgres_data:
  pgadmin_data:

networks:
  mynetwork: